#!/bin/sh

#  createManagedUser.sh
#  CBCreateUser
#
#  Created by Satendra Dagar on 18/12/17.
#  Copyright © 2017 Satendra Dagar. All rights reserved.

USER="drybarpos"
USRERNAME="drybarpos"


function GenerateAndSaveParentalPlist()
{
plist=`cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>com.apple.familycontrols.logging</key>
<dict>
<key>web</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
<key>iChat</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
<key>applications</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.iChatAgent</key>
<dict>
<key>Setting.parentalControls.forceChatLogging</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
<key>Setting.parentalControls</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
<key>Setting.parentalControls.forceAIMWhitelist</key>
<dict>
<key>value</key>
<false/>
<key>state</key>
<string>always</string>
</dict>
<key>Setting.parentalControls.forceJabberWhitelist</key>
<dict>
<key>value</key>
<false/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.Dictionary</key>
<dict>
<key>parentalControl</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.applicationaccess.new</key>
<dict>
<key>CFREnabled</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
<key>whiteList</key>
<dict>
<key>value</key>
<array>
<dict>
<key>displayName</key>
<string>Skype for Business</string>
<key>appID</key>
<data>+t4MAAAAAKwAAAABAAAABgAAAAIAAAAeY29tLm1pY3Jvc29mdC5Ta3lwZUZvckJ1c2luZXNzAAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app</string>
<key>subApps</key>
<array>
<dict>
<key>displayName</key>
<string>WLMKernel</string>
<key>appID</key>
<data>+t4MAAAAAKQAAAABAAAABgAAAAIAAAAXY29tLm1pY3Jvc29mdC53bG1rZXJuZWwAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/WLMKernel.framework/Versions/A/WLMKernel</string>
<key>bundleID</key>
<string>com.microsoft.wlmkernel</string>
</dict>
<dict>
<key>displayName</key>
<string>mbulocale</string>
<key>appID</key>
<data>+t4MAAAAAKQAAAABAAAABgAAAAIAAAAXY29tLm1pY3Jvc29mdC5tYnVsb2NhbGUAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/mbulocale.framework/Versions/A/mbulocale</string>
<key>bundleID</key>
<string>com.microsoft.mbulocale</string>
</dict>
<dict>
<key>displayName</key>
<string>mbuinstrument</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABgAAAAIAAAAbY29tLm1pY3Jvc29mdC5tYnVpbnN0cnVtZW50AAAAAAYAAAAPAAAABgAAAA4AAAABAAAACiqGSIb3Y2QGAgYAAAAAAAAAAAAGAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKQUw3OThLOThGWAAA</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/mbuinstrument.framework/Versions/A/mbuinstrument</string>
<key>bundleID</key>
<string>com.microsoft.mbuinstrument</string>
</dict>
<dict>
<key>displayName</key>
<string>WinCrypto</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAiY29tLm1pY3Jvc29mdC5mcmFtZXdvcmtzLndpbmNyeXB0bwAAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/WinCrypto.framework/Versions/A/WinCrypto</string>
<key>bundleID</key>
<string>com.microsoft.frameworks.wincrypto</string>
</dict>
<dict>
<key>displayName</key>
<string>Netlib</string>
<key>appID</key>
<data>+t4MAAAAAKAAAAABAAAABgAAAAIAAAAUY29tLm1pY3Jvc29mdC5uZXRsaWIAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/Netlib.framework/Versions/A/Netlib</string>
<key>bundleID</key>
<string>com.microsoft.netlib</string>
</dict>
<dict>
<key>displayName</key>
<string>mbukernel</string>
<key>appID</key>
<data>+t4MAAAAAKQAAAABAAAABgAAAAIAAAAXY29tLm1pY3Jvc29mdC5tYnVrZXJuZWwAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/mbukernel.framework/Versions/A/mbukernel</string>
<key>bundleID</key>
<string>com.microsoft.mbukernel</string>
</dict>
<dict>
<key>displayName</key>
<string>RDPKit</string>
<key>appID</key>
<data>+t4MAAAAAKAAAAABAAAABgAAAAIAAAAUY29tLm1pY3Jvc29mdC5yZHBraXQAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/RDPKit.framework/Versions/A/RDPKit</string>
<key>bundleID</key>
<string>com.microsoft.rdpkit</string>
</dict>
<dict>
<key>displayName</key>
<string>MicrosoftFontLibrary</string>
<key>appID</key>
<data>+t4MAAAAAKQAAAABAAAABgAAAAIAAAAVY29tLm1pY3Jvc29mdC5tYnVmb250AAAAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/MicrosoftFontLibrary.framework/Versions/A/MicrosoftFontLibrary</string>
<key>bundleID</key>
<string>com.microsoft.mbufont</string>
</dict>
<dict>
<key>displayName</key>
<string>RtmMediaStack.dylib</string>
<key>appID</key>
<data>+t4MAAAAAJwAAAABAAAABgAAAAIAAAANUnRtTWVkaWFTdGFjawAAAAAAAAYAAAAPAAAABgAAAA4AAAABAAAACiqGSIb3Y2QGAgYAAAAAAAAAAAAGAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKQUw3OThLOThGWAAA</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/RtmMediaStack.dylib</string>
<key>bundleID</key>
<string>com.unknown.RtmMediaStack</string>
</dict>
<dict>
<key>displayName</key>
<string>ssScreenVVS2.dylib</string>
<key>appID</key>
<data>+t4MAAAAAJgAAAABAAAABgAAAAIAAAAMc3NTY3JlZW5WVlMyAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/ssScreenVVS2.dylib</string>
<key>bundleID</key>
<string>com.unknown.ssScreenVVS2</string>
</dict>
<dict>
<key>displayName</key>
<string>libroottools.dylib</string>
<key>appID</key>
<data>+t4MAAAAAJgAAAABAAAABgAAAAIAAAAMbGlicm9vdHRvb2xzAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/libroottools.dylib</string>
<key>bundleID</key>
<string>com.unknown.libroottools</string>
</dict>
<dict>
<key>displayName</key>
<string>ADAL</string>
<key>appID</key>
<data>+t4MAAAAAKAAAAABAAAABgAAAAIAAAASY29tLm1pY3Jvc29mdC5BREFMAAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/ADAL.framework/Versions/A/ADAL</string>
<key>bundleID</key>
<string>com.microsoft.ADAL</string>
</dict>
<dict>
<key>displayName</key>
<string>IPA</string>
<key>appID</key>
<data>+t4MAAAAAKAAAAABAAAABgAAAAIAAAARY29tLm1pY3Jvc29mdC5JUEEAAAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/IPA</string>
<key>bundleID</key>
<string>com.microsoft.IPA</string>
</dict>
<dict>
<key>displayName</key>
<string>SkypeAppKit</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABgAAAAIAAAAZY29tLm1pY3Jvc29mdC5Ta3lwZUFwcEtpdAAAAAAAAAYAAAAPAAAABgAAAA4AAAABAAAACiqGSIb3Y2QGAgYAAAAAAAAAAAAGAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKQUw3OThLOThGWAAA</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/SkypeAppKit.framework/Versions/A/SkypeAppKit</string>
<key>bundleID</key>
<string>com.microsoft.SkypeAppKit</string>
</dict>
<dict>
<key>displayName</key>
<string>Model</string>
<key>appID</key>
<data>+t4MAAAAAKAAAAABAAAABgAAAAIAAAATY29tLm1pY3Jvc29mdC5Nb2RlbAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Model</string>
<key>bundleID</key>
<string>com.microsoft.Model</string>
</dict>
<dict>
<key>displayName</key>
<string>HockeySDK</string>
<key>appID</key>
<data>+t4MAAAAAKQAAAABAAAABgAAAAIAAAAVbmV0LmhvY2tleWFwcC5zZGsubWFjAAAAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/HockeySDK.framework/Versions/A/HockeySDK</string>
<key>bundleID</key>
<string>net.hockeyapp.sdk.mac</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftAppKit.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKwAAAABAAAABgAAAAIAAAAgY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRBcHBLaXQAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftAppKit.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftAppKit</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftCoreImage.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAjY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRDb3JlSW1hZ2UAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreImage.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreImage</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftObjectiveC.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAkY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRPYmplY3RpdmVDAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftObjectiveC.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftObjectiveC</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftXPC.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKwAAAABAAAABgAAAAIAAAAdY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRYUEMAAAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftXPC.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftXPC</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftCore.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKwAAAABAAAABgAAAAIAAAAeY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRDb3JlAAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCore.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCore</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftCoreGraphics.dylib</string>
<key>appID</key>
<data>+t4MAAAAALQAAAABAAAABgAAAAIAAAAmY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRDb3JlR3JhcGhpY3MAAAAAAAYAAAAPAAAABgAAAA4AAAABAAAACiqGSIb3Y2QGAgYAAAAAAAAAAAAGAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKQUw3OThLOThGWAAA</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreGraphics.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreGraphics</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftCoreData.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAiY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRDb3JlRGF0YQAAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreData.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreData</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftDispatch.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAiY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnREaXNwYXRjaAAAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftDispatch.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftDispatch</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftDarwin.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKwAAAABAAAABgAAAAIAAAAgY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnREYXJ3aW4AAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftDarwin.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftDarwin</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftQuartzCore.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAkY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRRdWFydHpDb3JlAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftQuartzCore.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftQuartzCore</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftIOKit.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKwAAAABAAAABgAAAAIAAAAfY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRJT0tpdAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFMNzk4Szk4RlgAAA==</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftIOKit.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftIOKit</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftCoreAudio.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAjY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRDb3JlQXVkaW8AAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreAudio.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreAudio</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftAVFoundation.dylib</string>
<key>appID</key>
<data>+t4MAAAAALQAAAABAAAABgAAAAIAAAAmY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRBVkZvdW5kYXRpb24AAAAAAAYAAAAPAAAABgAAAA4AAAABAAAACiqGSIb3Y2QGAgYAAAAAAAAAAAAGAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKQUw3OThLOThGWAAA</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftAVFoundation.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftAVFoundation</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftFoundation.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAkY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRGb3VuZGF0aW9uAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftFoundation.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftFoundation</string>
</dict>
<dict>
<key>displayName</key>
<string>libswiftCoreMedia.dylib</string>
<key>appID</key>
<data>+t4MAAAAALAAAAABAAAABgAAAAIAAAAjY29tLmFwcGxlLmR0LnJ1bnRpbWUuc3dpZnRDb3JlTWVkaWEAAAAABgAAAA8AAAAGAAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYAAAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAAAQAAAApBTDc5OEs5OEZYAAA=</data>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreMedia.dylib</string>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreMedia</string>
</dict>
</array>
<key>bundleID</key>
<string>com.microsoft.SkypeForBusiness</string>
</dict>
<dict>
<key>displayName</key>
<string>Go-Agent</string>
<key>path</key>
<string>/Library/Addigy/go-agent</string>
</dict>
<dict>
<key>displayName</key>
<string>RC</string>
<key>path</key>
<string>/Library/Application Support/plx/rc</string>
</dict>
<dict>
<key>displayName</key>
<string>Go-Utils</string>
<key>path</key>
<string>/Library/Addigy/go-utils</string>
</dict>
<dict>
<key>displayName</key>
<string>ScreenConnect</string>
<key>path</key>
<string>/opt/screenconnect-92fde59311b74250.app</string>
</dict>
<dict>
<key>displayName</key>
<string>Preview</string>
<key>appID</key>
<data>+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29tLmFwcGxlLlByZXZpZXcAAAAAAAAD</data>
<key>path</key>
<string>/Applications/Preview.app</string>
<key>bundleID</key>
<string>com.apple.Preview</string>
</dict>
<dict>
<key>displayName</key>
<string>Firefox</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app</string>
<key>subApps</key>
<array>
<dict>
<key>displayName</key>
<string>minidump-analyzer</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/crashreporter.app/Contents/MacOS/minidump-analyzer</string>
<key>bundleID</key>
<string>com.unknown.minidump-analyzer</string>
</dict>
<dict>
<key>displayName</key>
<string>libclearkey.dylib</string>
<key>appID</key>
<data>+t4MAAAAAEgAAAABAAAABwAAAAgAAAAU2W/cgau2rY5IYD2F0r+nR1qPRJYAAAAIAAAAFO7Okq91yofVhv762OG/Pxl2jI/W</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/Resources/gmp-clearkey/0.1/libclearkey.dylib</string>
<key>bundleID</key>
<string>com.unknown.libclearkey</string>
</dict>
<dict>
<key>displayName</key>
<string>pingsender</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/pingsender</string>
<key>bundleID</key>
<string>com.unknown.pingsender</string>
</dict>
<dict>
<key>displayName</key>
<string>libfreebl3.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libfreebl3.dylib</string>
<key>bundleID</key>
<string>com.unknown.libfreebl3</string>
</dict>
<dict>
<key>displayName</key>
<string>firefox-bin</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/firefox-bin</string>
<key>bundleID</key>
<string>com.unknown.firefox-bin</string>
</dict>
<dict>
<key>displayName</key>
<string>liblgpllibs.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/liblgpllibs.dylib</string>
<key>bundleID</key>
<string>com.unknown.liblgpllibs</string>
</dict>
<dict>
<key>displayName</key>
<string>libplugin_child_interpose.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libplugin_child_interpose.dylib</string>
<key>bundleID</key>
<string>com.unknown.libplugin_child_interpose</string>
</dict>
<dict>
<key>displayName</key>
<string>FirefoxCP</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/plugin-container.app</string>
<key>bundleID</key>
<string>org.mozilla.plugincontainer</string>
</dict>
<dict>
<key>displayName</key>
<string>libsoftokn3.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libsoftokn3.dylib</string>
<key>bundleID</key>
<string>com.unknown.libsoftokn3</string>
</dict>
<dict>
<key>displayName</key>
<string>XUL</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/XUL</string>
<key>bundleID</key>
<string>com.unknown.XUL</string>
</dict>
<dict>
<key>displayName</key>
<string>libmozavutil.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libmozavutil.dylib</string>
<key>bundleID</key>
<string>com.unknown.libmozavutil</string>
</dict>
<dict>
<key>displayName</key>
<string>libmozglue.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libmozglue.dylib</string>
<key>bundleID</key>
<string>com.unknown.libmozglue</string>
</dict>
<dict>
<key>displayName</key>
<string>Crash Reporter</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/crashreporter.app</string>
<key>bundleID</key>
<string>org.mozilla.crashreporter</string>
</dict>
<dict>
<key>displayName</key>
<string>libnssdbm3.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libnssdbm3.dylib</string>
<key>bundleID</key>
<string>com.unknown.libnssdbm3</string>
</dict>
<dict>
<key>displayName</key>
<string>libmozavcodec.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libmozavcodec.dylib</string>
<key>bundleID</key>
<string>com.unknown.libmozavcodec</string>
</dict>
<dict>
<key>displayName</key>
<string>Firefox Software Update</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/updater.app</string>
<key>bundleID</key>
<string>org.mozilla.updater</string>
</dict>
<dict>
<key>displayName</key>
<string>libnssckbi.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libnssckbi.dylib</string>
<key>bundleID</key>
<string>com.unknown.libnssckbi</string>
</dict>
<dict>
<key>displayName</key>
<string>libnss3.dylib</string>
<key>appID</key>
<data>+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAADgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkzNkg5NgAA</data>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libnss3.dylib</string>
<key>bundleID</key>
<string>com.unknown.libnss3</string>
</dict>
</array>
<key>bundleID</key>
<string>org.mozilla.firefox</string>
</dict>
</array>
<key>state</key>
<string>always</string>
</dict>
<key>familyControlsEnabled</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.coremediaio.support</key>
<dict>
<key>Device Access Allowed</key>
<dict>
<key>value</key>
<false/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.familycontrols.contentfilter</key>
<dict>
<key>restrictWeb</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
<key>useContentFilter</key>
<dict>
<key>value</key>
<true/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.gamed</key>
<dict>
<key>GKFeatureAddingGameCenterFriendsAllowed</key>
<dict>
<key>value</key>
<false/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.ironwood.support</key>
<dict>
<key>Profanity Allowed</key>
<dict>
<key>value</key>
<false/>
<key>state</key>
<string>always</string>
</dict>
<key>Assistant Allowed</key>
<dict>
<key>value</key>
<false/>
<key>state</key>
<string>always</string>
</dict>
<key>Ironwood Allowed</key>
<dict>
<key>value</key>
<false/>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.parentalcontrols</key>
<dict>
<key>prefsVersion</key>
<dict>
<key>value</key>
<integer>1</integer>
<key>state</key>
<string>always</string>
</dict>
</dict>
<key>com.apple.systempreferences</key>
<dict>
<key>com.apple.restrictTCC</key>
<dict>
<key>value</key>
<array>
<string>kTCCServiceAddressBook</string>
<string>kTCCServiceCalendar</string>
<string>kTCCServiceReminders</string>
<string>kTCCServiceTwitter</string>
<string>kTCCServiceFacebook</string>
</array>
<key>state</key>
<string>always</string>
</dict>
</dict>
</dict>
</plist>
EOF
`
echo "$plist" > /private/tmp/temp_control.plist
}


function GenerateAndSaveDockPlist()
{
plist=`cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>last-messagetrace-stamp</key>
<real>535703661.409293</real>
<key>mod-count</key>
<integer>30</integer>
<key>persistent-apps</key>
<array>
<dict>
<key>tile-data</key>
<dict>
<key>file-data</key>
<dict>
<key>_CFURLString</key>
<string>/Applications/Firefox.app</string>
<key>_CFURLStringType</key>
<integer>0</integer>
</dict>
</dict>
</dict>
<dict>
<key>tile-data</key>
<dict>
<key>file-data</key>
<dict>
<key>_CFURLString</key>
<string>/Applications/Skype for Business.app</string>
<key>_CFURLStringType</key>
<integer>0</integer>
</dict>
</dict>
</dict>
</array>
<key>persistent-others</key>
<array>
<dict>
<key>GUID</key>
<integer>1009514988</integer>
<key>tile-data</key>
<dict>
<key>arrangement</key>
<integer>2</integer>
<key>book</key>
<data>
Ym9va0ADAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAPAIAAAUAAAABAQAAVXNlcnMA
AAANAAAAAQEAAHNhdGVuZHJhc2luZ2gAAAAJAAAAAQEA
AERvd25sb2FkcwAAAAwAAAABBgAABAAAABQAAAAsAAAA
CAAAAAQDAADBxAcAAAAAAAgAAAAEAwAAMTUIAAAAAAAI
AAAABAMAADQ1CAAAAAAADAAAAAEGAABUAAAAZAAAAHQA
AAAIAAAAAAQAAEG+/b6TAAAAGAAAAAECAAACAAAAAAAA
AA8AAAAAAAAAAAAAAAAAAAAIAAAABAMAAAEAAAAAAAAA
BAAAAAMDAAD1AQAACAAAAAEJAABmaWxlOi8vLwoAAAAB
AQAARGV2bG9wbWVudAAACAAAAAQDAAAAANS/IgAAAAgA
AAAABAAAQb6Z8VUAAAAkAAAAAQEAADRERTFFMjFFLTk4
NDQtM0E5OC1BMzg4LUIxNTk3RkMzOTI4MBgAAAABAgAA
gQAAAAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAv
AAAAAAAAAAEFAACpAAAAAQIAADBhNWZmZmE1ZGMxY2E4
NjI2Yzc5YzM1OWQyY2E2ZGU0MzA5YTZmZTU7MDAwMDAw
MDA7MDAwMDAwMDA7MDAwMDAwMDAwMDAwMDAyMDtjb20u
YXBwbGUuYXBwLXNhbmRib3gucmVhZC13cml0ZTswMTsw
MTAwMDAwODswMDAwMDAwMDAwMDgzNTM0Oy91c2Vycy9z
YXRlbmRyYXNpbmdoL2Rvd25sb2FkcwAAAADMAAAA/v//
/wEAAAAAAAAAEAAAAAQQAABAAAAAAAAAAAUQAACEAAAA
AAAAABAQAACoAAAAAAAAAEAQAACYAAAAAAAAAAIgAAB0
AQAAAAAAAAUgAADkAAAAAAAAABAgAAD0AAAAAAAAABEg
AAAoAQAAAAAAABIgAAAIAQAAAAAAABMgAAAYAQAAAAAA
ACAgAABUAQAAAAAAADAgAACAAQAAAAAAAAHAAADIAAAA
AAAAABHAAAAUAAAAAAAAABLAAADYAAAAAAAAAIDwAACI
AQAAAAAAAA==
</data>
<key>displayas</key>
<integer>0</integer>
<key>file-data</key>
<dict>
<key>_CFURLString</key>
<string>file:///Users/$USER/Downloads/</string>
<key>_CFURLStringType</key>
<integer>15</integer>
</dict>
<key>file-label</key>
<string>Downloads</string>
<key>file-mod-date</key>
<integer>3587100719</integer>
<key>file-type</key>
<integer>2</integer>
<key>parent-mod-date</key>
<integer>3587100728</integer>
<key>preferreditemsize</key>
<integer>-1</integer>
<key>showas</key>
<integer>1</integer>
</dict>
<key>tile-type</key>
<string>directory-tile</string>
</dict>
</array>
<key>trash-full</key>
<false/>
<key>version</key>
<integer>1</integer>
<key>wvous-bl-corner</key>
<integer>3</integer>
<key>wvous-bl-modifier</key>
<integer>0</integer>
<key>wvous-br-corner</key>
<integer>5</integer>
<key>wvous-br-modifier</key>
<integer>0</integer>
<key>wvous-tl-corner</key>
<integer>4</integer>
<key>wvous-tl-modifier</key>
<integer>0</integer>
<key>wvous-tr-corner</key>
<integer>2</integer>
<key>wvous-tr-modifier</key>
<integer>0</integer>
</dict>
</plist>
EOF
`
echo "$plist" > /private/tmp/temp_dock.plist
}

function ApplyParentalControl()
{
sudo dscl . -mcximport /Users/$USER /private/tmp/temp_control.plist
}

function ApplyDockControl()
{
sudo mv /private/tmp/temp_dock.plist /Users/$USER/Library/Preferences/com.apple.dock.plist
}
function Cleanup()
{
rm /private/tmp/temp_control.plist
}

function Main()
{
GenerateAndSaveParentalPlist
ApplyParentalControl
GenerateAndSaveDockPlist
ApplyDockControl
Cleanup
}
Main
