#!/bin/sh

#  createManagedUser.sh
#  CBCreateUser
#
#  Created by Satendra Dagar on 18/12/17.
#  Copyright © 2017 Satendra Dagar. All rights reserved.

USER="drybarpos"
USRERNAME="drybarpos"


function GenerateAndSaveParentalPlist()
{
plist=`cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>com.apple.Dictionary</key>
<dict>
<key>parentalControl</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
</dict>
<key>com.apple.applicationaccess.new</key>
<dict>
<key>CFREnabled</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
<key>familyControlsEnabled</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
<key>whiteList</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<array>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKwAAAABAAAABgAAAAIAAAAeY29t
Lm1pY3Jvc29mdC5Ta3lwZUZvckJ1c2luZXNz
AAAAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoq
hkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAA
AAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAA
AAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACkFM
Nzk4Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.microsoft.SkypeForBusiness</string>
<key>displayName</key>
<string>Skype for Business</string>
<key>path</key>
<string>/Applications/Skype for Business.app</string>
<key>subApps</key>
<array>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKQAAAABAAAA
BgAAAAIAAAAXY29tLm1p
Y3Jvc29mdC53bG1rZXJu
ZWwAAAAABgAAAA8AAAAG
AAAADgAAAAEAAAAKKoZI
hvdjZAYCBgAAAAAAAAAA
AAYAAAAOAAAAAAAAAAoq
hkiG92NkBgENAAAAAAAA
AAAACwAAAAAAAAAKc3Vi
amVjdC5PVQAAAAAAAQAA
AApBTDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.microsoft.wlmkernel</string>
<key>displayName</key>
<string>WLMKernel</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/WLMKernel.framework/Versions/A/WLMKernel</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKQAAAABAAAA
BgAAAAIAAAAXY29tLm1p
Y3Jvc29mdC5tYnVsb2Nh
bGUAAAAABgAAAA8AAAAG
AAAADgAAAAEAAAAKKoZI
hvdjZAYCBgAAAAAAAAAA
AAYAAAAOAAAAAAAAAAoq
hkiG92NkBgENAAAAAAAA
AAAACwAAAAAAAAAKc3Vi
amVjdC5PVQAAAAAAAQAA
AApBTDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.microsoft.mbulocale</string>
<key>displayName</key>
<string>mbulocale</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/mbulocale.framework/Versions/A/mbulocale</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BgAAAAIAAAAbY29tLm1p
Y3Jvc29mdC5tYnVpbnN0
cnVtZW50AAAAAAYAAAAP
AAAABgAAAA4AAAABAAAA
CiqGSIb3Y2QGAgYAAAAA
AAAAAAAGAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKQUw3OThLOThG
WAAA
</data>
<key>bundleID</key>
<string>com.microsoft.mbuinstrument</string>
<key>displayName</key>
<string>mbuinstrument</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/mbuinstrument.framework/Versions/A/mbuinstrument</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAiY29tLm1p
Y3Jvc29mdC5mcmFtZXdv
cmtzLndpbmNyeXB0bwAA
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.microsoft.frameworks.wincrypto</string>
<key>displayName</key>
<string>WinCrypto</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/WinCrypto.framework/Versions/A/WinCrypto</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKAAAAABAAAA
BgAAAAIAAAAUY29tLm1p
Y3Jvc29mdC5uZXRsaWIA
AAAGAAAADwAAAAYAAAAO
AAAAAQAAAAoqhkiG92Nk
BgIGAAAAAAAAAAAABgAA
AA4AAAAAAAAACiqGSIb3
Y2QGAQ0AAAAAAAAAAAAL
AAAAAAAAAApzdWJqZWN0
Lk9VAAAAAAABAAAACkFM
Nzk4Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.microsoft.netlib</string>
<key>displayName</key>
<string>Netlib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/Netlib.framework/Versions/A/Netlib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKQAAAABAAAA
BgAAAAIAAAAXY29tLm1p
Y3Jvc29mdC5tYnVrZXJu
ZWwAAAAABgAAAA8AAAAG
AAAADgAAAAEAAAAKKoZI
hvdjZAYCBgAAAAAAAAAA
AAYAAAAOAAAAAAAAAAoq
hkiG92NkBgENAAAAAAAA
AAAACwAAAAAAAAAKc3Vi
amVjdC5PVQAAAAAAAQAA
AApBTDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.microsoft.mbukernel</string>
<key>displayName</key>
<string>mbukernel</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/mbukernel.framework/Versions/A/mbukernel</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKAAAAABAAAA
BgAAAAIAAAAUY29tLm1p
Y3Jvc29mdC5yZHBraXQA
AAAGAAAADwAAAAYAAAAO
AAAAAQAAAAoqhkiG92Nk
BgIGAAAAAAAAAAAABgAA
AA4AAAAAAAAACiqGSIb3
Y2QGAQ0AAAAAAAAAAAAL
AAAAAAAAAApzdWJqZWN0
Lk9VAAAAAAABAAAACkFM
Nzk4Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.microsoft.rdpkit</string>
<key>displayName</key>
<string>RDPKit</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/RDPKit.framework/Versions/A/RDPKit</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKQAAAABAAAA
BgAAAAIAAAAVY29tLm1p
Y3Jvc29mdC5tYnVmb250
AAAAAAAABgAAAA8AAAAG
AAAADgAAAAEAAAAKKoZI
hvdjZAYCBgAAAAAAAAAA
AAYAAAAOAAAAAAAAAAoq
hkiG92NkBgENAAAAAAAA
AAAACwAAAAAAAAAKc3Vi
amVjdC5PVQAAAAAAAQAA
AApBTDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.microsoft.mbufont</string>
<key>displayName</key>
<string>MicrosoftFontLibrary</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/MicrosoftFontLibrary.framework/Versions/A/MicrosoftFontLibrary</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAJwAAAABAAAA
BgAAAAIAAAANUnRtTWVk
aWFTdGFjawAAAAAAAAYA
AAAPAAAABgAAAA4AAAAB
AAAACiqGSIb3Y2QGAgYA
AAAAAAAAAAAGAAAADgAA
AAAAAAAKKoZIhvdjZAYB
DQAAAAAAAAAAAAsAAAAA
AAAACnN1YmplY3QuT1UA
AAAAAAEAAAAKQUw3OThL
OThGWAAA
</data>
<key>bundleID</key>
<string>com.unknown.RtmMediaStack</string>
<key>displayName</key>
<string>RtmMediaStack.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/RtmMediaStack.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAJgAAAABAAAA
BgAAAAIAAAAMc3NTY3Jl
ZW5WVlMyAAAABgAAAA8A
AAAGAAAADgAAAAEAAAAK
KoZIhvdjZAYCBgAAAAAA
AAAAAAYAAAAOAAAAAAAA
AAoqhkiG92NkBgENAAAA
AAAAAAAACwAAAAAAAAAK
c3ViamVjdC5PVQAAAAAA
AQAAAApBTDc5OEs5OEZY
AAA=
</data>
<key>bundleID</key>
<string>com.unknown.ssScreenVVS2</string>
<key>displayName</key>
<string>ssScreenVVS2.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/ssScreenVVS2.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAJgAAAABAAAA
BgAAAAIAAAAMbGlicm9v
dHRvb2xzAAAABgAAAA8A
AAAGAAAADgAAAAEAAAAK
KoZIhvdjZAYCBgAAAAAA
AAAAAAYAAAAOAAAAAAAA
AAoqhkiG92NkBgENAAAA
AAAAAAAACwAAAAAAAAAK
c3ViamVjdC5PVQAAAAAA
AQAAAApBTDc5OEs5OEZY
AAA=
</data>
<key>bundleID</key>
<string>com.unknown.libroottools</string>
<key>displayName</key>
<string>libroottools.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/Frameworks/libroottools.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKAAAAABAAAA
BgAAAAIAAAASY29tLm1p
Y3Jvc29mdC5BREFMAAAA
AAAGAAAADwAAAAYAAAAO
AAAAAQAAAAoqhkiG92Nk
BgIGAAAAAAAAAAAABgAA
AA4AAAAAAAAACiqGSIb3
Y2QGAQ0AAAAAAAAAAAAL
AAAAAAAAAApzdWJqZWN0
Lk9VAAAAAAABAAAACkFM
Nzk4Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.microsoft.ADAL</string>
<key>displayName</key>
<string>ADAL</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/ADAL.framework/Versions/A/ADAL</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKAAAAABAAAA
BgAAAAIAAAARY29tLm1p
Y3Jvc29mdC5JUEEAAAAA
AAAGAAAADwAAAAYAAAAO
AAAAAQAAAAoqhkiG92Nk
BgIGAAAAAAAAAAAABgAA
AA4AAAAAAAAACiqGSIb3
Y2QGAQ0AAAAAAAAAAAAL
AAAAAAAAAApzdWJqZWN0
Lk9VAAAAAAABAAAACkFM
Nzk4Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.microsoft.IPA</string>
<key>displayName</key>
<string>IPA</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Frameworks/IPA.framework/Versions/A/IPA</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BgAAAAIAAAAZY29tLm1p
Y3Jvc29mdC5Ta3lwZUFw
cEtpdAAAAAAAAAYAAAAP
AAAABgAAAA4AAAABAAAA
CiqGSIb3Y2QGAgYAAAAA
AAAAAAAGAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKQUw3OThLOThG
WAAA
</data>
<key>bundleID</key>
<string>com.microsoft.SkypeAppKit</string>
<key>displayName</key>
<string>SkypeAppKit</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/SkypeAppKit.framework/Versions/A/SkypeAppKit</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKAAAAABAAAA
BgAAAAIAAAATY29tLm1p
Y3Jvc29mdC5Nb2RlbAAA
AAAGAAAADwAAAAYAAAAO
AAAAAQAAAAoqhkiG92Nk
BgIGAAAAAAAAAAAABgAA
AA4AAAAAAAAACiqGSIb3
Y2QGAQ0AAAAAAAAAAAAL
AAAAAAAAAApzdWJqZWN0
Lk9VAAAAAAABAAAACkFM
Nzk4Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.microsoft.Model</string>
<key>displayName</key>
<string>Model</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/Model.framework/Versions/A/Model</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKQAAAABAAAA
BgAAAAIAAAAVbmV0Lmhv
Y2tleWFwcC5zZGsubWFj
AAAAAAAABgAAAA8AAAAG
AAAADgAAAAEAAAAKKoZI
hvdjZAYCBgAAAAAAAAAA
AAYAAAAOAAAAAAAAAAoq
hkiG92NkBgENAAAAAAAA
AAAACwAAAAAAAAAKc3Vi
amVjdC5PVQAAAAAAAQAA
AApBTDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>net.hockeyapp.sdk.mac</string>
<key>displayName</key>
<string>HockeySDK</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/HockeySDK.framework/Versions/A/HockeySDK</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKwAAAABAAAA
BgAAAAIAAAAgY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRBcHBLaXQAAAAG
AAAADwAAAAYAAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAABgAAAA4A
AAAAAAAACiqGSIb3Y2QG
AQ0AAAAAAAAAAAALAAAA
AAAAAApzdWJqZWN0Lk9V
AAAAAAABAAAACkFMNzk4
Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftAppKit</string>
<key>displayName</key>
<string>libswiftAppKit.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftAppKit.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAjY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRDb3JlSW1hZ2UA
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreImage</string>
<key>displayName</key>
<string>libswiftCoreImage.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreImage.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAkY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRPYmplY3RpdmVD
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftObjectiveC</string>
<key>displayName</key>
<string>libswiftObjectiveC.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftObjectiveC.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKwAAAABAAAA
BgAAAAIAAAAdY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRYUEMAAAAAAAAG
AAAADwAAAAYAAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAABgAAAA4A
AAAAAAAACiqGSIb3Y2QG
AQ0AAAAAAAAAAAALAAAA
AAAAAApzdWJqZWN0Lk9V
AAAAAAABAAAACkFMNzk4
Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftXPC</string>
<key>displayName</key>
<string>libswiftXPC.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftXPC.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKwAAAABAAAA
BgAAAAIAAAAeY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRDb3JlAAAAAAAG
AAAADwAAAAYAAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAABgAAAA4A
AAAAAAAACiqGSIb3Y2QG
AQ0AAAAAAAAAAAALAAAA
AAAAAApzdWJqZWN0Lk9V
AAAAAAABAAAACkFMNzk4
Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCore</string>
<key>displayName</key>
<string>libswiftCore.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCore.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALQAAAABAAAA
BgAAAAIAAAAmY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRDb3JlR3JhcGhp
Y3MAAAAAAAYAAAAPAAAA
BgAAAA4AAAABAAAACiqG
SIb3Y2QGAgYAAAAAAAAA
AAAGAAAADgAAAAAAAAAK
KoZIhvdjZAYBDQAAAAAA
AAAAAAsAAAAAAAAACnN1
YmplY3QuT1UAAAAAAAEA
AAAKQUw3OThLOThGWAAA
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreGraphics</string>
<key>displayName</key>
<string>libswiftCoreGraphics.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreGraphics.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAiY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRDb3JlRGF0YQAA
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreData</string>
<key>displayName</key>
<string>libswiftCoreData.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreData.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAiY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnREaXNwYXRjaAAA
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftDispatch</string>
<key>displayName</key>
<string>libswiftDispatch.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftDispatch.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKwAAAABAAAA
BgAAAAIAAAAgY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnREYXJ3aW4AAAAG
AAAADwAAAAYAAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAABgAAAA4A
AAAAAAAACiqGSIb3Y2QG
AQ0AAAAAAAAAAAALAAAA
AAAAAApzdWJqZWN0Lk9V
AAAAAAABAAAACkFMNzk4
Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftDarwin</string>
<key>displayName</key>
<string>libswiftDarwin.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftDarwin.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAkY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRRdWFydHpDb3Jl
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftQuartzCore</string>
<key>displayName</key>
<string>libswiftQuartzCore.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftQuartzCore.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKwAAAABAAAA
BgAAAAIAAAAfY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRJT0tpdAAAAAAG
AAAADwAAAAYAAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAABgAAAA4A
AAAAAAAACiqGSIb3Y2QG
AQ0AAAAAAAAAAAALAAAA
AAAAAApzdWJqZWN0Lk9V
AAAAAAABAAAACkFMNzk4
Szk4RlgAAA==
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftIOKit</string>
<key>displayName</key>
<string>libswiftIOKit.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftIOKit.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAjY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRDb3JlQXVkaW8A
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreAudio</string>
<key>displayName</key>
<string>libswiftCoreAudio.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreAudio.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALQAAAABAAAA
BgAAAAIAAAAmY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRBVkZvdW5kYXRp
b24AAAAAAAYAAAAPAAAA
BgAAAA4AAAABAAAACiqG
SIb3Y2QGAgYAAAAAAAAA
AAAGAAAADgAAAAAAAAAK
KoZIhvdjZAYBDQAAAAAA
AAAAAAsAAAAAAAAACnN1
YmplY3QuT1UAAAAAAAEA
AAAKQUw3OThLOThGWAAA
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftAVFoundation</string>
<key>displayName</key>
<string>libswiftAVFoundation.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftAVFoundation.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAkY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRGb3VuZGF0aW9u
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftFoundation</string>
<key>displayName</key>
<string>libswiftFoundation.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftFoundation.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAALAAAAABAAAA
BgAAAAIAAAAjY29tLmFw
cGxlLmR0LnJ1bnRpbWUu
c3dpZnRDb3JlTWVkaWEA
AAAABgAAAA8AAAAGAAAA
DgAAAAEAAAAKKoZIhvdj
ZAYCBgAAAAAAAAAAAAYA
AAAOAAAAAAAAAAoqhkiG
92NkBgENAAAAAAAAAAAA
CwAAAAAAAAAKc3ViamVj
dC5PVQAAAAAAAQAAAApB
TDc5OEs5OEZYAAA=
</data>
<key>bundleID</key>
<string>com.apple.dt.runtime.swiftCoreMedia</string>
<key>displayName</key>
<string>libswiftCoreMedia.dylib</string>
<key>path</key>
<string>/Applications/Skype for Business.app/Contents/Frameworks/libswiftCoreMedia.dylib</string>
</dict>
</array>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
LmFwcGxlLlByZXZpZXcAAAAAAAAD
</data>
<key>bundleID</key>
<string>com.apple.Preview</string>
<key>displayName</key>
<string>Preview</string>
<key>path</key>
<string>/Applications/Preview.app</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAABwAAAAYAAAAPAAAA
DgAAAAAAAAAKKoZIhvdjZAYBCQAAAAAAAAAA
AAYAAAAGAAAABgAAAA8AAAAOAAAAAQAAAAoq
hkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAK
KoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAAAAEAAAAKNDNBUTkz
Nkg5NgAA
</data>
<key>bundleID</key>
<string>org.mozilla.firefox</string>
<key>displayName</key>
<string>Firefox</string>
<key>path</key>
<string>/Applications/Firefox.app</string>
<key>subApps</key>
<array>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.minidump-analyzer</string>
<key>displayName</key>
<string>minidump-analyzer</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/crashreporter.app/Contents/MacOS/minidump-analyzer</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAEgAAAABAAAA
BwAAAAgAAAAU2W/cgau2
rY5IYD2F0r+nR1qPRJYA
AAAIAAAAFO7Okq91yofV
hv762OG/Pxl2jI/W
</data>
<key>bundleID</key>
<string>com.unknown.libclearkey</string>
<key>displayName</key>
<string>libclearkey.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/Resources/gmp-clearkey/0.1/libclearkey.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.pingsender</string>
<key>displayName</key>
<string>pingsender</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/pingsender</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libfreebl3</string>
<key>displayName</key>
<string>libfreebl3.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libfreebl3.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.firefox-bin</string>
<key>displayName</key>
<string>firefox-bin</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/firefox-bin</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.liblgpllibs</string>
<key>displayName</key>
<string>liblgpllibs.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/liblgpllibs.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libplugin_child_interpose</string>
<key>displayName</key>
<string>libplugin_child_interpose.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libplugin_child_interpose.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>org.mozilla.plugincontainer</string>
<key>displayName</key>
<string>FirefoxCP</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/plugin-container.app</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libsoftokn3</string>
<key>displayName</key>
<string>libsoftokn3.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libsoftokn3.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.XUL</string>
<key>displayName</key>
<string>XUL</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/XUL</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libmozavutil</string>
<key>displayName</key>
<string>libmozavutil.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libmozavutil.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libmozglue</string>
<key>displayName</key>
<string>libmozglue.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libmozglue.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>org.mozilla.crashreporter</string>
<key>displayName</key>
<string>Crash Reporter</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/crashreporter.app</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libnssdbm3</string>
<key>displayName</key>
<string>libnssdbm3.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libnssdbm3.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libmozavcodec</string>
<key>displayName</key>
<string>libmozavcodec.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libmozavcodec.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>org.mozilla.updater</string>
<key>displayName</key>
<string>Firefox Software Update</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/updater.app</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libnssckbi</string>
<key>displayName</key>
<string>libnssckbi.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libnssckbi.dylib</string>
</dict>
<dict>
<key>appID</key>
<data>
+t4MAAAAAKgAAAABAAAA
BwAAAAYAAAAPAAAADgAA
AAAAAAAKKoZIhvdjZAYB
CQAAAAAAAAAAAAYAAAAG
AAAABgAAAA8AAAAOAAAA
AQAAAAoqhkiG92NkBgIG
AAAAAAAAAAAADgAAAAAA
AAAKKoZIhvdjZAYBDQAA
AAAAAAAAAAsAAAAAAAAA
CnN1YmplY3QuT1UAAAAA
AAEAAAAKNDNBUTkzNkg5
NgAA
</data>
<key>bundleID</key>
<string>com.unknown.libnss3</string>
<key>displayName</key>
<string>libnss3.dylib</string>
<key>path</key>
<string>/Applications/Firefox.app/Contents/MacOS/libnss3.dylib</string>
</dict>
</array>
</dict>
</array>
</dict>
</dict>
<key>com.apple.coremediaio.support</key>
<dict>
<key>Device Access Allowed</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<false/>
</dict>
</dict>
<key>com.apple.familycontrols.contentfilter</key>
<dict>
<key>restrictWeb</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
<key>useContentFilter</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
</dict>
<key>com.apple.familycontrols.logging</key>
<dict>
<key>applications</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
<key>iChat</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
<key>web</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
</dict>
<key>com.apple.gamed</key>
<dict>
<key>GKFeatureAddingGameCenterFriendsAllowed</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<false/>
</dict>
</dict>
<key>com.apple.iChatAgent</key>
<dict>
<key>Setting.parentalControls</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
<key>Setting.parentalControls.forceAIMWhitelist</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<false/>
</dict>
<key>Setting.parentalControls.forceChatLogging</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<true/>
</dict>
<key>Setting.parentalControls.forceJabberWhitelist</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<false/>
</dict>
</dict>
<key>com.apple.ironwood.support</key>
<dict>
<key>Assistant Allowed</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<false/>
</dict>
<key>Ironwood Allowed</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<false/>
</dict>
<key>Profanity Allowed</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<false/>
</dict>
</dict>
<key>com.apple.parentalcontrols</key>
<dict>
<key>prefsVersion</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<integer>1</integer>
</dict>
</dict>
<key>com.apple.systempreferences</key>
<dict>
<key>com.apple.restrictTCC</key>
<dict>
<key>state</key>
<string>always</string>
<key>value</key>
<array>
<string>kTCCServiceAddressBook</string>
<string>kTCCServiceCalendar</string>
<string>kTCCServiceReminders</string>
<string>kTCCServiceTwitter</string>
<string>kTCCServiceFacebook</string>
</array>
</dict>
</dict>
</dict>
</plist>
EOF
`
echo "$plist" > /private/tmp/temp_control.plist
}


function GenerateAndSaveDockPlist()
{
plist=`cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>last-messagetrace-stamp</key>
<real>535703661.409293</real>
<key>mod-count</key>
<integer>30</integer>
<key>persistent-apps</key>
<array>
<dict>
<key>tile-data</key>
<dict>
<key>file-data</key>
<dict>
<key>_CFURLString</key>
<string>/Applications/Firefox.app</string>
<key>_CFURLStringType</key>
<integer>0</integer>
</dict>
</dict>
</dict>
<dict>
<key>tile-data</key>
<dict>
<key>file-data</key>
<dict>
<key>_CFURLString</key>
<string>/Applications/Skype for Business.app</string>
<key>_CFURLStringType</key>
<integer>0</integer>
</dict>
</dict>
</dict>
</array>
<key>persistent-others</key>
<array>
<dict>
<key>GUID</key>
<integer>1009514988</integer>
<key>tile-data</key>
<dict>
<key>arrangement</key>
<integer>2</integer>
<key>book</key>
<data>
Ym9va0ADAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAPAIAAAUAAAABAQAAVXNlcnMA
AAANAAAAAQEAAHNhdGVuZHJhc2luZ2gAAAAJAAAAAQEA
AERvd25sb2FkcwAAAAwAAAABBgAABAAAABQAAAAsAAAA
CAAAAAQDAADBxAcAAAAAAAgAAAAEAwAAMTUIAAAAAAAI
AAAABAMAADQ1CAAAAAAADAAAAAEGAABUAAAAZAAAAHQA
AAAIAAAAAAQAAEG+/b6TAAAAGAAAAAECAAACAAAAAAAA
AA8AAAAAAAAAAAAAAAAAAAAIAAAABAMAAAEAAAAAAAAA
BAAAAAMDAAD1AQAACAAAAAEJAABmaWxlOi8vLwoAAAAB
AQAARGV2bG9wbWVudAAACAAAAAQDAAAAANS/IgAAAAgA
AAAABAAAQb6Z8VUAAAAkAAAAAQEAADRERTFFMjFFLTk4
NDQtM0E5OC1BMzg4LUIxNTk3RkMzOTI4MBgAAAABAgAA
gQAAAAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAv
AAAAAAAAAAEFAACpAAAAAQIAADBhNWZmZmE1ZGMxY2E4
NjI2Yzc5YzM1OWQyY2E2ZGU0MzA5YTZmZTU7MDAwMDAw
MDA7MDAwMDAwMDA7MDAwMDAwMDAwMDAwMDAyMDtjb20u
YXBwbGUuYXBwLXNhbmRib3gucmVhZC13cml0ZTswMTsw
MTAwMDAwODswMDAwMDAwMDAwMDgzNTM0Oy91c2Vycy9z
YXRlbmRyYXNpbmdoL2Rvd25sb2FkcwAAAADMAAAA/v//
/wEAAAAAAAAAEAAAAAQQAABAAAAAAAAAAAUQAACEAAAA
AAAAABAQAACoAAAAAAAAAEAQAACYAAAAAAAAAAIgAAB0
AQAAAAAAAAUgAADkAAAAAAAAABAgAAD0AAAAAAAAABEg
AAAoAQAAAAAAABIgAAAIAQAAAAAAABMgAAAYAQAAAAAA
ACAgAABUAQAAAAAAADAgAACAAQAAAAAAAAHAAADIAAAA
AAAAABHAAAAUAAAAAAAAABLAAADYAAAAAAAAAIDwAACI
AQAAAAAAAA==
</data>
<key>displayas</key>
<integer>0</integer>
<key>file-data</key>
<dict>
<key>_CFURLString</key>
<string>file:///Users/$USER/Downloads/</string>
<key>_CFURLStringType</key>
<integer>15</integer>
</dict>
<key>file-label</key>
<string>Downloads</string>
<key>file-mod-date</key>
<integer>3587100719</integer>
<key>file-type</key>
<integer>2</integer>
<key>parent-mod-date</key>
<integer>3587100728</integer>
<key>preferreditemsize</key>
<integer>-1</integer>
<key>showas</key>
<integer>1</integer>
</dict>
<key>tile-type</key>
<string>directory-tile</string>
</dict>
</array>
<key>trash-full</key>
<false/>
<key>version</key>
<integer>1</integer>
<key>wvous-bl-corner</key>
<integer>3</integer>
<key>wvous-bl-modifier</key>
<integer>0</integer>
<key>wvous-br-corner</key>
<integer>5</integer>
<key>wvous-br-modifier</key>
<integer>0</integer>
<key>wvous-tl-corner</key>
<integer>4</integer>
<key>wvous-tl-modifier</key>
<integer>0</integer>
<key>wvous-tr-corner</key>
<integer>2</integer>
<key>wvous-tr-modifier</key>
<integer>0</integer>
</dict>
</plist>
EOF
`
echo "$plist" > /private/tmp/temp_dock.plist
}

function ApplyParentalControl()
{
sudo dscl . -mcximport /Users/$USER /private/tmp/temp_control.plist
}

function ApplyDockControl()
{
sudo mv /private/tmp/temp_dock.plist /Users/$USER/Library/Preferences/com.apple.dock.plist
}
function Cleanup()
{
rm /private/tmp/temp_control.plist
}

function Main()
{
GenerateAndSaveParentalPlist
ApplyParentalControl
GenerateAndSaveDockPlist
ApplyDockControl
Cleanup
}
Main
